// Mocks generated by Mockito 5.3.2 from annotations
// in save_contacts_tdd/test/persentation/blox/contacts_bloc/contacts_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:save_contacts_tdd/core/error/failure.dart' as _i6;
import 'package:save_contacts_tdd/domain/entities/contact_entity/contact.dart'
    as _i7;
import 'package:save_contacts_tdd/domain/repositories/contact_repository/contact_repository.dart'
    as _i2;
import 'package:save_contacts_tdd/domain/usecases/contacts_usecases/add_contact_usecase.dart'
    as _i4;
import 'package:save_contacts_tdd/domain/usecases/contacts_usecases/get_contacts_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContactRepository_0 extends _i1.SmartFake
    implements _i2.ContactRepository {
  _FakeContactRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddContactUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddContactUseCase extends _i1.Mock implements _i4.AddContactUseCase {
  @override
  _i2.ContactRepository get contactRepository => (super.noSuchMethod(
        Invocation.getter(#contactRepository),
        returnValue: _FakeContactRepository_0(
          this,
          Invocation.getter(#contactRepository),
        ),
        returnValueForMissingStub: _FakeContactRepository_0(
          this,
          Invocation.getter(#contactRepository),
        ),
      ) as _i2.ContactRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Contact>>> call(
          _i7.Contact? contact) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [contact],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Contact>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Contact>>(
          this,
          Invocation.method(
            #call,
            [contact],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Contact>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Contact>>(
          this,
          Invocation.method(
            #call,
            [contact],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Contact>>>);
}

/// A class which mocks [GetContactsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetContactsUseCase extends _i1.Mock
    implements _i8.GetContactsUseCase {
  @override
  _i2.ContactRepository get contactRepository => (super.noSuchMethod(
        Invocation.getter(#contactRepository),
        returnValue: _FakeContactRepository_0(
          this,
          Invocation.getter(#contactRepository),
        ),
        returnValueForMissingStub: _FakeContactRepository_0(
          this,
          Invocation.getter(#contactRepository),
        ),
      ) as _i2.ContactRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Contact>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Contact>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Contact>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Contact>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Contact>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Contact>>>);
}
