// Mocks generated by Mockito 5.3.2 from annotations
// in save_contacts_tdd/test/domain/usecases/contacts_usecases/get_contacts_usecase.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:save_contacts_tdd/core/error/failure.dart' as _i5;
import 'package:save_contacts_tdd/domain/entities/contact_entity/contact.dart'
    as _i6;
import 'package:save_contacts_tdd/domain/repositories/contact_repository/contact_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactRepository extends _i1.Mock implements _i3.ContactRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Contact>>> getContacts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Contact>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Contact>>(
          this,
          Invocation.method(
            #getContacts,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Contact>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Contact>>(
          this,
          Invocation.method(
            #getContacts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Contact>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Contact>>> addContact(
          _i6.Contact? contact) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContact,
          [contact],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Contact>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Contact>>(
          this,
          Invocation.method(
            #addContact,
            [contact],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Contact>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Contact>>(
          this,
          Invocation.method(
            #addContact,
            [contact],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Contact>>>);
}
